SET FOREIGN_KEY_CHECKS = 0;
DELETE FROM  tb_account where institution_id = "4";
DELETE FROM  tb_account_alert where institution_id = "4";
DELETE FROM  tb_account_detail where institution_id = "4";
DELETE FROM  tb_account_receivable where institution_id = "4";
DELETE FROM  tb_activity_action where institution_id = "4";
DELETE FROM  tb_activity_evaluation where institution_id = "4";
DELETE FROM  tb_activity_evaluation_praise where institution_id = "4";
DELETE FROM  tb_activity_evaluation_reply where institution_id = "4";
DELETE FROM  tb_activity_info where institution_id = "4";
DELETE FROM  tb_activity_participator where institution_id = "4";
DELETE FROM  tb_activity_photo where institution_id = "4";
DELETE FROM  tb_activity_range_define where institution_id = "4";
DELETE FROM  tb_activity_range_obj where institution_id = "4";
DELETE FROM  tb_advertisement where institution_id = "4";
DELETE FROM  tb_app_version where institution_id = "4";
DELETE FROM  tb_applicant_info where institution_id = "4";
DELETE FROM  tb_assist_move_check where institution_id = "4";
DELETE FROM  tb_balance where institution_id = "4";
DELETE FROM  tb_balance_bill_detail where institution_id = "4";
DELETE FROM  tb_bath_care where institution_id = "4";
DELETE FROM  tb_bed_change where institution_id = "4";
DELETE FROM  tb_bed_change_history where institution_id = "4";
DELETE FROM  tb_bed_info where institution_id = "4";
DELETE FROM  tb_bedclothes where institution_id = "4";
DELETE FROM  tb_building_info where institution_id = "4";
DELETE FROM  tb_card_account where institution_id = "4";
DELETE FROM  tb_card_account_detail where institution_id = "4";
DELETE FROM  tb_care_record_info where institution_id = "4";
DELETE FROM  tb_cart where institution_id = "4";
DELETE FROM  tb_cash_bill where institution_id = "4";
DELETE FROM  tb_cash_bill_detail where institution_id = "4";
DELETE FROM  tb_change_diapers where institution_id = "4";
DELETE FROM  tb_change_urinbag where institution_id = "4";
DELETE FROM  tb_chg_prone_position where institution_id = "4";
DELETE FROM  tb_chg_stomackthroat where institution_id = "4";
DELETE FROM  tb_chg_urinethroat where institution_id = "4";
DELETE FROM  tb_complaint where institution_id = "4";
DELETE FROM  tb_constraints_evaluation where institution_id = "4";
DELETE FROM  tb_consume_service_record where institution_id = "4";
DELETE FROM  tb_contract where institution_id = "4";
DELETE FROM  tb_crm_complaint_handle where institution_id = "4";
DELETE FROM  tb_crm_complaint_info where institution_id = "4";
DELETE FROM  tb_crm_follow_up where institution_id = "4";
DELETE FROM  tb_crm_visit_elder where institution_id = "4";
DELETE FROM  tb_cs_deduct_recrd where institution_id = "4";
DELETE FROM  tb_cs_record where institution_id = "4";
DELETE FROM  tb_cs_seat_info where institution_id = "4";
DELETE FROM  tb_cs_to_do where institution_id = "4";
DELETE FROM  tb_daily_account where institution_id = "4";
DELETE FROM  tb_daily_account_detail where institution_id = "4";
DELETE FROM  tb_dailycare_package where institution_id = "4";
DELETE FROM  tb_dailycare_register where institution_id = "4";
DELETE FROM  tb_dailycare_shuttle where institution_id = "4";
DELETE FROM  tb_denture_care where institution_id = "4";
DELETE FROM  tb_dispatch where institution_id = "4";
DELETE FROM  tb_donation_info where institution_id = "4";
DELETE FROM  tb_dr_drug_info where institution_id = "4";
DELETE FROM  tb_drug_fee_rec where institution_id = "4";
DELETE FROM  tb_elder where institution_id = "4";
DELETE FROM  tb_elder_ability_assess where institution_id = "4";
DELETE FROM  tb_elder_contract where institution_id = "4";
DELETE FROM  tb_elder_deposit_mgr where institution_id = "4";
DELETE FROM  tb_elder_diet_info where institution_id = "4";
DELETE FROM  tb_elder_diet_package_recd where institution_id = "4";
DELETE FROM  tb_elder_discharge_in where institution_id = "4";
DELETE FROM  tb_elder_discharge_info where institution_id = "4";
DELETE FROM  tb_elder_discharge_out where institution_id = "4";
DELETE FROM  tb_elder_expense_discount where institution_id = "4";
DELETE FROM  tb_elder_go_back where institution_id = "4";
DELETE FROM  tb_elder_go_back_detail where institution_id = "4";
DELETE FROM  tb_elder_in_notify where institution_id = "4";
DELETE FROM  tb_elder_interview_recd where institution_id = "4";
DELETE FROM  tb_elder_party where institution_id = "4";
DELETE FROM  tb_elder_price_proposal where institution_id = "4";
DELETE FROM  tb_elder_service_modify where institution_id = "4";
DELETE FROM  tb_elder_service_recd where institution_id = "4";
DELETE FROM  tb_employee_info where institution_id = "4";
DELETE FROM  tb_en_diagnosischeck where institution_id = "4";
DELETE FROM  tb_en_diagnosisregistration where institution_id = "4";
DELETE FROM  tb_en_doctoradvice where institution_id = "4";
DELETE FROM  tb_en_elder_indcident where institution_id = "4";
DELETE FROM  tb_en_feed_medicine where institution_id = "4";
DELETE FROM  tb_en_medicalrecords where institution_id = "4";
DELETE FROM  tb_en_prescription where institution_id = "4";
DELETE FROM  tb_en_tubefeed_info where institution_id = "4";
DELETE FROM  tb_en_woud_assessment where institution_id = "4";
DELETE FROM  tb_en_wound_wash where institution_id = "4";
DELETE FROM  tb_equipment_repair where institution_id = "4";
DELETE FROM  tb_eva_task where institution_id = "4";
DELETE FROM  tb_expense_item where institution_id = "4";
DELETE FROM  tb_expense_standard where institution_id = "4";
DELETE FROM  tb_external_inspection where institution_id = "4";
DELETE FROM  tb_fd_daily_diet where institution_id = "4";
DELETE FROM  tb_fd_daily_diet_like where institution_id = "4";
DELETE FROM  tb_fd_meal_diction where institution_id = "4";
DELETE FROM  tb_fd_week_set_meal where institution_id = "4";
DELETE FROM  tb_floor_info where institution_id = "4";
DELETE FROM  tb_general_in where institution_id = "4";
DELETE FROM  tb_general_out where institution_id = "4";
DELETE FROM  tb_goods_fee_rec where institution_id = "4";
DELETE FROM  tb_health_basic_info where institution_id = "4";
DELETE FROM  tb_hr_activity_record where institution_id = "4";
DELETE FROM  tb_hr_certificate where institution_id = "4";
DELETE FROM  tb_hr_employ_train where institution_id = "4";
DELETE FROM  tb_hr_employer_chg where institution_id = "4";
DELETE FROM  tb_hr_employer_resume where institution_id = "4";
DELETE FROM  tb_hr_employer_salary where institution_id = "4";
DELETE FROM  tb_hr_labor_contract where institution_id = "4";
DELETE FROM  tb_hr_leave_record where institution_id = "4";
DELETE FROM  tb_hr_performance where institution_id = "4";
DELETE FROM  tb_hr_reward_punish where institution_id = "4";
DELETE FROM  tb_hr_salary_item where institution_id = "4";
DELETE FROM  tb_hr_salary_sheet where institution_id = "4";
DELETE FROM  tb_hr_skill_display where institution_id = "4";
DELETE FROM  tb_import_log where institution_id = "4";
DELETE FROM  tb_institution where institution_id = "4";
DELETE FROM  tb_institution_param_info where institution_id = "4";
DELETE FROM  tb_invoice_file where institution_id = "4";
DELETE FROM  tb_invoice_info where institution_id = "4";
DELETE FROM  tb_invoice_receivable_deatil where institution_id = "4";
DELETE FROM  tb_invoice_shop_info where institution_id = "4";
DELETE FROM  tb_life_satus where institution_id = "4";
DELETE FROM  tb_notice where institution_id = "4";
DELETE FROM  tb_notice_bulletin where institution_id = "4";
DELETE FROM  tb_order_dinner where institution_id = "4";
DELETE FROM  tb_pac_mouth_care where institution_id = "4";
DELETE FROM  tb_patrol_monitor_info where institution_id = "4";
DELETE FROM  tb_pay_order where institution_id = "4";
DELETE FROM  tb_pay_order_detail where institution_id = "4";
DELETE FROM  tb_pay_trading_flow where institution_id = "4";
DELETE FROM  tb_pcw_check_count where institution_id = "4";
DELETE FROM  tb_pcw_check_count_res where institution_id = "4";
DELETE FROM  tb_pcw_dress_care where institution_id = "4";
DELETE FROM  tb_position_alert_info where institution_id = "4";
DELETE FROM  tb_position_elder_device where institution_id = "4";
DELETE FROM  tb_position_fence_info where institution_id = "4";
DELETE FROM  tb_position_locator_device where institution_id = "4";
DELETE FROM  tb_position_past_location where institution_id = "4";
DELETE FROM  tb_position_real_location where institution_id = "4";
DELETE FROM  tb_process_instance where institution_id = "4";
DELETE FROM  tb_process_instance_node where institution_id = "4";
DELETE FROM  tb_process_model where institution_id = "4";
DELETE FROM  tb_provider_agreement where institution_id = "4";
DELETE FROM  tb_provider_agreement_detail where institution_id = "4";
DELETE FROM  tb_re_entry where institution_id = "4";
DELETE FROM  tb_re_entry_sheet where institution_id = "4";
DELETE FROM  tb_re_goods where institution_id = "4";
DELETE FROM  tb_re_goods_class where institution_id = "4";
DELETE FROM  tb_re_inventory where institution_id = "4";
DELETE FROM  tb_re_inventory_alert where institution_id = "4";
DELETE FROM  tb_re_inventory_plan where institution_id = "4";
DELETE FROM  tb_re_outhouse where institution_id = "4";
DELETE FROM  tb_re_outhouse_sheet where institution_id = "4";
DELETE FROM  tb_re_stocktacking where institution_id = "4";
DELETE FROM  tb_re_supplier where institution_id = "4";
DELETE FROM  tb_re_transfer where institution_id = "4";
DELETE FROM  tb_re_transfer_detail where institution_id = "4";
DELETE FROM  tb_re_warehouse where institution_id = "4";
DELETE FROM  tb_receivable where institution_id = "4";
DELETE FROM  tb_receivable_deatil where institution_id = "4";
DELETE FROM  tb_recharge_num where institution_id = "4";
DELETE FROM  tb_recharge_payment where institution_id = "4";
DELETE FROM  tb_recharge_record where institution_id = "4";
DELETE FROM  tb_recure_assess_rpt where institution_id = "4";
DELETE FROM  tb_recure_detail where institution_id = "4";
DELETE FROM  tb_recure_excute where institution_id = "4";
DELETE FROM  tb_recure_program where institution_id = "4";
DELETE FROM  tb_region_info where institution_id = "4";
DELETE FROM  tb_region_room where institution_id = "4";
DELETE FROM  tb_registration where institution_id = "4";
DELETE FROM  tb_registration_visit where institution_id = "4";
DELETE FROM  tb_renew where institution_id = "4";
DELETE FROM  tb_renew_detail where institution_id = "4";
DELETE FROM  tb_renew_status where institution_id = "4";
DELETE FROM  tb_restriction_observe where institution_id = "4";
DELETE FROM  tb_room_info where institution_id = "4";
DELETE FROM  tb_self_inspection where institution_id = "4";
DELETE FROM  tb_serve_fee_rec where institution_id = "4";
DELETE FROM  tb_serve_item where institution_id = "4";

DELETE FROM  tb_service_change where institution_id = "4";

DELETE FROM  tb_service_package where institution_id = "4";
DELETE FROM  tb_service_package_items where institution_id = "4";
DELETE FROM  tb_service_profileinfo where institution_id = "4";
DELETE FROM  tb_service_task where institution_id = "4";
DELETE FROM  tb_service_task_chg where institution_id = "4";
DELETE FROM  tb_service_task_exec where institution_id = "4";
DELETE FROM  tb_service_task_exec_eva where institution_id = "4";
DELETE FROM  tb_serviceplan where institution_id = "4";
DELETE FROM  tb_serviceplan_detail where institution_id = "4";
DELETE FROM  tb_shift_arrange where institution_id = "4";
DELETE FROM  tb_shift_arrange_main where institution_id = "4";
DELETE FROM  tb_shift_arrange_rule where institution_id = "4";
DELETE FROM  tb_shift_arrange_rule_detail where institution_id = "4";
DELETE FROM  tb_shift_arrange_rule_main where institution_id = "4";
DELETE FROM  tb_shift_emp_arrange_rule where institution_id = "4";
DELETE FROM  tb_shiftchg_brief where institution_id = "4";
DELETE FROM  tb_single_discount where institution_id = "4";
DELETE FROM  tb_single_discount_item where institution_id = "4";
DELETE FROM  tb_standard_price where institution_id = "4";
DELETE FROM  tb_sys_elder_event where institution_id = "4";
DELETE FROM  tb_sys_enquipment where institution_id = "4";
DELETE FROM  tb_sys_event_dic where institution_id = "4";
DELETE FROM  tb_sys_feedback where institution_id = "4";
DELETE FROM  tb_sys_module_column where institution_id = "4";
DELETE FROM  tb_sys_organization where institution_id = "4";
DELETE FROM  tb_sys_shift where institution_id = "4";
DELETE FROM  tb_sys_shift_depart where institution_id = "4";
DELETE FROM  tb_sys_shift_room where institution_id = "4";
DELETE FROM  tb_trim_nails where institution_id = "4";
DELETE FROM  tb_tubefeed_in where institution_id = "4";
DELETE FROM  tb_venue_info where institution_id = "4";
DELETE FROM  tb_venue_open_period where institution_id = "4";
DELETE FROM  tb_venue_subscribe where institution_id = "4";
DELETE FROM  tb_venue_subscribe_sum where institution_id = "4";
DELETE FROM  tb_vital_sign where institution_id = "4";
DELETE FROM  tb_volunt_haircut where institution_id = "4";
DELETE FROM  tb_volunteer_info where institution_id = "4";
DELETE FROM  tb_wash_dress where institution_id = "4";

-- 特殊
DELETE FROM tb_service_category where maintenance_type != '0' and institution_id = "4";
DELETE FROM tb_service_item where maintenance_type != '0' and institution_id = "4";
-- 初始值
/*DELETE FROM tb_process_model;*/
/*DELETE FROM tb_process_model_node;*/
-- 初始值
/*DELETE FROM tb_slides;*/
-- 初始值
/*DELETE FROM tb_sys_module;*/
-- 初始值
/*DELETE FROM tb_vital_sign_threshold_config;*/


/** 无机构id
DELETE FROM  tb_expense_levy;
DELETE FROM  tb_applicant_history;
DELETE FROM  tb_balance_receivable;
DELETE FROM  tb_dispatch_detail;
DELETE FROM  tb_expense_levy_detail;
DELETE FROM  tb_expense_standard_attribute;
DELETE FROM  tb_family_history;
DELETE FROM  tb_goods_fee_rec_detail;
DELETE FROM  tb_institution_rel;
DELETE FROM  tb_living_habit;
DELETE FROM  tb_medical;
DELETE FROM  tb_medical_detail;
DELETE FROM  tb_notice_bulletin_terminal;
DELETE FROM  tb_order_dinner_detail;
DELETE FROM  tb_past_history;
DELETE FROM  tb_person_history;
DELETE FROM  tb_personal_info;
DELETE FROM  tb_personal_life_environment;
DELETE FROM  tb_rel_elder_party_elder;
DELETE FROM  tb_service_summary;
DELETE FROM  tb_service_task_process;
DELETE FROM  tb_service_task_temp;
DELETE FROM  tb_serviceitem_publish;
DELETE FROM  tb_sys_org_menu;
DELETE FROM  tb_sys_province;
DELETE FROM  tb_timing_task;
DELETE FROM  tb_interface_config; 
 */


SET FOREIGN_KEY_CHECKS = 1;